### ISSUE TITLE
Plugin + WP 4 + blog in subdirectory = can't upload files?

### ISSUE THREAD

**Issue by xorserer** [GoogleCloudPlatform/appengine-wordpress-plugin#26]
I'm happily using the plugin with Wordpress 3.9, and everything is working correctly.
However, when trying to use it with WP 4.x, the uploading of files stops working. Any file I try to upload fails with a generic `HTTP error` or similar.

I should note that the blog is in a subdirectory: users access it through `www.mydomain.com/blog/` and also all of its files are in a subdirectory called `blog` under the app's directory.

I've changed `WP_HOME` and `WP_SITEURL` in `wp-config.php` to

```
define('WP_SITEURL', $protocol_to_use . $_SERVER['HTTP_HOST'] . '/blog');
define('WP_HOME', $protocol_to_use . $_SERVER['HTTP_HOST'] . '/blog');
```

and also edited my `app.yaml` to

```
application: my-app
version: 1
runtime: php55
api_version: 1

handlers:
- url: /blog/(.*\.(htm|html|css|js|ico|jpg|png|gif|json))$
  static_files: blog/\1
  upload: blog/.*\.(htm|html|css|js|ico|jpg|png|gif|json)$
  application_readable: true

- url: /blog/(.*\.(eot|svg|ttf|woff|woff2|otf))$
  static_files: blog/\1
  upload: blog/.*\.(eot|svg|ttf|woff|woff2|otf)$

- url: /blog/wp-admin/(.+)
  script: blog/wp-admin/\1
  secure: always

- url: /blog/wp-admin/
  script: blog/wp-admin/index.php
  secure: always

- url: /blog/wp-login.php
  script: blog/wp-login.php
  secure: always

- url: /blog/wp-cron.php
  script: blog/wp-cron.php
  login: admin

- url: /blog/xmlrpc.php
  script: blog/xmlrpc.php

- url: /blog/wp-(.+).php
  script: blog/wp-\1.php

- url: /blog(/.+)?/?
  script: blog/index.php

- url: /.*
  script: main-page/index.php

<< more handlers for stuff not under /blog >>
```

This configuration seems to work for everything _except_ uploading - I've checked the server logs and all requests are handled by the correct handler. Also, uploading doesn't produce any 404 error or any request that is not handled.

**For testing's sake, I've removed the prefix `/blog` from all `url:` lines and also reverted WP's `SITE_*` variables, and then everything is working again.**

Do you know what I'm doing wrong? Do you have a working example of WP 4 working under a subdirectory?
Thanks
